# states.py

# Состояния для ConversationHandler
(
    MAIN_MENU,
    VIEW_DEPARTMENTS,
    VIEW_EMPLOYEES,
    VIEW_EMPLOYEE_DETAILS,
    ADD_DEPARTMENT,
    ADD_EMPLOYEE_START,
    ADD_EMPLOYEE_NAME,
    ADD_EMPLOYEE_BIRTH,
    ADD_EMPLOYEE_TG_ID,
    EDIT_EMPLOYEE,
    CONFIRM_DELETE,
    EDIT_EMPLOYEE_FIELD,
    EDIT_DEPARTMENT,
    DELETE_EMPLOYEE,
    DELETE_DEPARTMENT,
    EDIT_DEPARTMENT_NAME,
    EDIT_EMPLOYEE_NAME,
    EDIT_EMPLOYEE_BIRTH
) = range(18)
